steps:
    - name: 'gcr.io/cloud-builders/docker'
      dir:  'courses/machine_learning/deepdive/06_structured/pipelines/containers/traintuned'   # remove-for-manual
      args: [ 'build', '-t', 'gcr.io/confluent-98f26/babyweight-pipeline-traintuned:latest', '.' ]
images:
    - 'gcr.io/confluent-98f26/babyweight-pipeline-traintuned:latest'
